In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv('spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [49]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [50]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.25)

In [52]:
len(X_test)

1393

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7489))

In [54]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [55]:
model.fit(X_train_count, y_train)

MultinomialNB()

In [56]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [57]:
X_test_count = v.transform(X_test)

In [59]:
y_predicted = model.predict(X_test_count)
y_predicted

array([0, 0, 0, ..., 1, 0, 0], shape=(1393,))

In [60]:
model.score(X_test_count, y_test)

0.9863603732950467

**Sklearn Pipeline**

In [61]:
from sklearn.pipeline import Pipeline
clf = Pipeline([('vectorizer', CountVectorizer()),
                ('nb', MultinomialNB())
                ])

In [62]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [63]:
clf.predict(X_test)

array([0, 0, 0, ..., 1, 0, 0], shape=(1393,))

In [64]:
clf.score(X_test, y_test)

0.9863603732950467

In [65]:
clf.predict(emails)

array([0, 1])